language: python
python:
    - "3.4"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - coverage run --source phalerts phalerts_test.py
after_success:
    - coveralls
